sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - iojs
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
script: "sudo $(which npm) test"
# script:
  # - npm test
after_success:
  - npm run semantic-release
